# Generated by Django 3.2.10 on 2022-01-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0002_robin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robin',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
